In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
df_train = pd.read_csv('df_train_formatted.csv')

In [2]:
df_photos = pd.read_csv('df_photos.csv')

In [3]:
df_photos

photo_id  photographer_username  stats_views  stats_downloads
0      bygTaBey1Xk                   3509            8               10
1      gXSFnk2a9V4                   4243           11               11
2      grg6-DNJuaU                   4959           11               11
3      sO42hhChB1c                    713            9                8
4      tkk8_HakQ98                   1244            9                8
...            ...                    ...          ...              ...
24995  rZQq3bdOsJU                   4430            2                5
24996  swQ3JS8e-Fs                   2592            1                5
24997  pZroun8cH1w                   8171            0                1
24998  JqOvq9ypB4w                   4723            3                7
24999  DItZ9r6Pt30                   3324            0                0

[25000 rows x 4 columns]

In [6]:
image_ids = [1,2,3]
additional_features = ['conversion_country', 'photographer_username', 'stats_views', 'stats_downloads']
feats = torch.tensor(df_photos.iloc[image_ids][additional_features[1:]].values)

In [7]:
feats

tensor([[4243,   11,   11],
        [4959,   11,   11],
        [ 713,    9,    8]])

In [8]:
user_counts = df_train.anonymous_user_id.value_counts()
users_atleast_once = user_counts[user_counts > 1].index

df_train_ = df_train[df_train.anonymous_user_id.isin(users_atleast_once)]
df_train_

converted_at conversion_type  keyword  photo_id  \
0        2023-05-09 11:03:40.445        download    28805      3681   
2        2023-05-09 11:17:33.417        download      242     19155   
3        2023-05-09 11:32:03.943        download     1977     16727   
4        2023-05-09 11:36:56.557        download    28805     16531   
6        2023-05-09 11:42:40.599        download     3261     16253   
...                          ...             ...      ...       ...   
7055024   2023-10-30 02:22:30.02        download    28805      8204   
7055025  2023-10-30 02:45:31.647        download    28805      2462   
7055026  2023-10-30 03:11:39.734        download       79      5292   
7055027  2023-10-30 03:12:15.223        download     1124      3312   
7055028  2023-10-30 03:24:28.108        download      239     17683   

         anonymous_user_id  conversion_country  photographer_username  \
0                        0                  52                   5630   
2                        2                 178                   7468   
3                        3                  97                   3479   
4                        4                  97                   5659   
6                        6                 216                   1608   
...                    ...                 ...                    ...   
7055024             414481                 112                   3794   
7055025            3528595                 112                   2080   
7055026            1570771                  44                   3558   
7055027             639993                  88                   2952   
7055028            1347371                  44                   2857   

         stats_views  stats_downloads  
0                 11               11  
2                 11               11  
3                 11               11  
4                 11               11  
6                 11               11  
...              ...              ...  
7055024           11               11  
7055025           11               11  
7055026           11               11  
7055027            4                3  
7055028            7                6  

[4665441 rows x 9 columns]

In [16]:
user_in_test = df_test['anonymous_user_id'].unique()
df_train_2 = df_train[df_train['anonymous_user_id'].isin(user_in_test)]
df_train_2

converted_at conversion_type  keyword  photo_id  \
0        2023-05-09 11:03:40.445        download    28805      3681   
2        2023-05-09 11:17:33.417        download      242     19155   
6        2023-05-09 11:42:40.599        download     3261     16253   
10       2023-05-09 12:39:21.898        download     1462     19615   
11       2023-05-09 12:46:13.895        download    28805     21926   
...                          ...             ...      ...       ...   
7055023  2023-10-30 01:55:22.427        download      321      9059   
7055024   2023-10-30 02:22:30.02        download    28805      8204   
7055025  2023-10-30 02:45:31.647        download    28805      2462   
7055027  2023-10-30 03:12:15.223        download     1124      3312   
7055028  2023-10-30 03:24:28.108        download      239     17683   

         anonymous_user_id  conversion_country  photographer_username  \
0                        0                  52                   5630   
2                        2                 178                   7468   
6                        6                 216                   1608   
10                      10                  71                   5880   
11                      11                  52                   6024   
...                    ...                 ...                    ...   
7055023            1907623                  35                   5882   
7055024             414481                 112                   3794   
7055025            3528595                 112                   2080   
7055027             639993                  88                   2952   
7055028            1347371                  44                   2857   

         stats_views  stats_downloads  
0                 11               11  
2                 11               11  
6                 11               11  
10                10               10  
11                11               10  
...              ...              ...  
7055023           10               11  
7055024           11               11  
7055025           11               11  
7055027            4                3  
7055028            7                6  

[1710353 rows x 9 columns]

In [17]:
df_train_3 = df_train_2[df_train_2['anonymous_user_id'].isin(users_atleast_once)]
df_train_3

converted_at conversion_type  keyword  photo_id  \
0        2023-05-09 11:03:40.445        download    28805      3681   
2        2023-05-09 11:17:33.417        download      242     19155   
6        2023-05-09 11:42:40.599        download     3261     16253   
10       2023-05-09 12:39:21.898        download     1462     19615   
11       2023-05-09 12:46:13.895        download    28805     21926   
...                          ...             ...      ...       ...   
7055023  2023-10-30 01:55:22.427        download      321      9059   
7055024   2023-10-30 02:22:30.02        download    28805      8204   
7055025  2023-10-30 02:45:31.647        download    28805      2462   
7055027  2023-10-30 03:12:15.223        download     1124      3312   
7055028  2023-10-30 03:24:28.108        download      239     17683   

         anonymous_user_id  conversion_country  photographer_username  \
0                        0                  52                   5630   
2                        2                 178                   7468   
6                        6                 216                   1608   
10                      10                  71                   5880   
11                      11                  52                   6024   
...                    ...                 ...                    ...   
7055023            1907623                  35                   5882   
7055024             414481                 112                   3794   
7055025            3528595                 112                   2080   
7055027             639993                  88                   2952   
7055028            1347371                  44                   2857   

         stats_views  stats_downloads  
0                 11               11  
2                 11               11  
6                 11               11  
10                10               10  
11                11               10  
...              ...              ...  
7055023           10               11  
7055024           11               11  
7055025           11               11  
7055027            4                3  
7055028            7                6  

[1543923 rows x 9 columns]

In [18]:
df_train_3.to_csv('df_train_cleaned.csv', index=False)

In [19]:
keyword_lookup = fm_model.keyword_lookup
df_train['keyword'] = df_train['keyword'].apply(lambda x: keyword_lookup[x])

In [23]:
user_lookup = fm_model.user_lookup
df_train['anonymous_user_id'] = df_train['anonymous_user_id'].apply(lambda x: user_lookup[x])
df_train

converted_at conversion_type  keyword     photo_id  \
0        2023-05-09 11:03:40.445        download    28805  jlV2k_Fx0fc   
1        2023-05-09 11:12:05.109        download    28805  yNGQ830uFB4   
2        2023-05-09 11:17:33.417        download      242  BFsm5vldl2I   
3        2023-05-09 11:32:03.943        download     1977  -cKXtsJWU-I   
4        2023-05-09 11:36:56.557        download    28805  CEeoDFpVxxw   
...                          ...             ...      ...          ...   
7055025  2023-10-30 02:45:31.647        download    28805  mawU2PoJWfU   
7055026  2023-10-30 03:11:39.734        download       79  BCuxVP5WEsU   
7055027  2023-10-30 03:12:15.223        download     1124  7Vesk70cnI4   
7055028  2023-10-30 03:24:28.108        download      239  60RIlM9JVLs   
7055029  2023-10-30 03:40:56.759        download      483  xulIYVIbYIc   

         anonymous_user_id  conversion_country  photographer_username  \
0                        0                  52                   5630   
1                        1                  44                   7616   
2                        2                 178                   7468   
3                        3                  97                   3479   
4                        4                  97                   5659   
...                    ...                 ...                    ...   
7055025            3528595                 112                   2080   
7055026            1570771                  44                   3558   
7055027             639993                  88                   2952   
7055028            1347371                  44                   2857   
7055029            3665915                 216                   3818   

         stats_views  stats_downloads  
0                 11               11  
1                 11               11  
2                 11               11  
3                 11               11  
4                 11               11  
...              ...              ...  
7055025           11               11  
7055026           11               11  
7055027            4                3  
7055028            7                6  
7055029           11               11  

[7055030 rows x 9 columns]

In [24]:
image_lookup = fm_model.image_lookup
df_train['photo_id'] = df_train['photo_id'].apply(lambda x: image_lookup[x])
df_train

converted_at conversion_type  keyword  photo_id  \
0        2023-05-09 11:03:40.445        download    28805      3681   
1        2023-05-09 11:12:05.109        download    28805      4880   
2        2023-05-09 11:17:33.417        download      242     19155   
3        2023-05-09 11:32:03.943        download     1977     16727   
4        2023-05-09 11:36:56.557        download    28805     16531   
...                          ...             ...      ...       ...   
7055025  2023-10-30 02:45:31.647        download    28805      2462   
7055026  2023-10-30 03:11:39.734        download       79      5292   
7055027  2023-10-30 03:12:15.223        download     1124      3312   
7055028  2023-10-30 03:24:28.108        download      239     17683   
7055029  2023-10-30 03:40:56.759        download      483      7034   

         anonymous_user_id  conversion_country  photographer_username  \
0                        0                  52                   5630   
1                        1                  44                   7616   
2                        2                 178                   7468   
3                        3                  97                   3479   
4                        4                  97                   5659   
...                    ...                 ...                    ...   
7055025            3528595                 112                   2080   
7055026            1570771                  44                   3558   
7055027             639993                  88                   2952   
7055028            1347371                  44                   2857   
7055029            3665915                 216                   3818   

         stats_views  stats_downloads  
0                 11               11  
1                 11               11  
2                 11               11  
3                 11               11  
4                 11               11  
...              ...              ...  
7055025           11               11  
7055026           11               11  
7055027            4                3  
7055028            7                6  
7055029           11               11  

[7055030 rows x 9 columns]

In [25]:
df_train.to_csv('df_train_formatted.csv', index=False)

In [9]:
from implicit_als import ALSModel
als_model = ALSModel()

In [10]:
df_test = pd.read_csv('df_test.csv')
df_test['anonymous_user_id'] = df_test['anonymous_user_id'].apply(lambda x: als_model.user_lookup[x])
df_test

converted_at conversion_type                keyword  \
0        2023-02-18 22:18:48.126        download                coconut   
1        2023-02-18 22:23:01.029        download                  scary   
2        2023-02-18 23:05:06.289        download       Iphone wallpaper   
3        2023-02-19 00:00:10.436        download  australian cattle dog   
4        2023-02-19 01:01:08.747        download            lawn mowing   
...                          ...             ...                    ...   
1763753  2023-12-16 22:19:11.714        download       sunny background   
1763754  2023-12-16 23:45:55.757        download                 horses   
1763755  2023-12-16 23:46:56.796        download          Frozen bubble   
1763756  2023-12-16 23:49:48.494        download         night portrait   
1763757  2023-12-16 23:50:42.524        download            dark clouds   

            photo_id  anonymous_user_id  conversion_country  \
0        E95Lpkg-bgc            3608188                 216   
1        7CME6Wlgrdk            1365343                 216   
2        tQk3y00flv4            3646653                  46   
3        zo-c4LbkSM8            3306187                 103   
4        LlHgaeBwYVE            3665916                  71   
...              ...                ...                 ...   
1763753  yJJpSoCB5YE            4347531                 231   
1763754  P6JRr7-FxLw            4343789                  71   
1763755  RgTI2KaQ5N4            4347532                 216   
1763756  JXUfF7HYfMo            4347533                  97   
1763757  LM4X_cIjjQ8            4347534                  35   

         photographer_username  stats_views  stats_downloads  
0                         3223           11               11  
1                          592           11               11  
2                         1681           11               11  
3                         1768            6                6  
4                         6446           11               11  
...                        ...          ...              ...  
1763753                   6073           10               11  
1763754                   2837           10               11  
1763755                     97           11               11  
1763756                   3266           10               11  
1763757                    824            9                7  

[1763758 rows x 9 columns]

In [11]:
from sklearn.preprocessing import minmax_scale
w_normalized = minmax_scale(als_model.user_downloads, axis=0)
w_normalized, w_normalized[0].max(), w_normalized[0].min(), w_normalized[-1].max(), w_normalized[-1].min(), w_normalized[0].mean()

TypeError: Sparse data was passed, but dense data is required. Use '.toarray()' to convert to a dense numpy array.

In [7]:
w_normalized[0].max(), w_normalized[0].min(), w_normalized[-1].max(), w_normalized[-1].min(), w_normalized[0].mean()

(0.036515125617800626, 0.0, 0.0, 0.0, 4.000000000000002e-05)

In [10]:
als_model.user_downloads, w_normalized

(<4347535x25000 sparse matrix of type '<class 'numpy.float64'>'
 	with 6518700 stored elements in Compressed Sparse Row format>,
 <4347535x25000 sparse matrix of type '<class 'numpy.float64'>'
 	with 6518700 stored elements in Compressed Sparse Row format>)

In [13]:
als_model.user_downloads.max(), als_model.user_downloads.min()
# als_model.user_downloads


(498.38396870280985, 0.0)

In [16]:
from fm import FMModel
fm_model = FMModel(additional_features=[], features_sizes=[])
# fm_model.train(df_train, batch_size=8192, epochs=10)
# fm_model.save('fm_model_new.pth')

In [ ]:
from eval import eval
df_test = pd.read_csv('df_test.csv')
eval(df_test, fm_model)

In [2]:
from fm import FMModel
fm_model = FMModel(additional_features=[], features_sizes=[])
fm_model.load('fm_model_1.pth')

In [4]:
fm_model.model

FM(
  (embedding): Embedding(4401341, 128, sparse=True)
  (fc): Embedding(4401341, 1, sparse=True)
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)

In [14]:
# fm_model.model.eval()

userid = '2f9c6ac4-02c8-4d0f-82b3-0482a82ab0bf'
# fm_model.search(userid, 'cbd gummy')

In [3]:
fm_model.keyword_lookup['cbd gummy0n']

28805

In [5]:
a = len(fm_model.all_users), len(fm_model.all_images), len(fm_model.keyword_dict)
a, sum(a)

((4347535, 25000, 28805), 4401340)

In [3]:
fm_model.model.offsets

array([      0, 4347535, 4372535])

In [6]:
4347535+25000

4372535

In [12]:
t = torch.LongTensor([[0,0,28805]]).cuda()
fm_model.model.eval()
fm_model.model(t)

tensor([1.], device='cuda:0', grad_fn=<ViewBackward0>)

In [13]:
fm_model.model

FM(
  (embedding): Embedding(4401341, 128, sparse=True)
  (fc): Embedding(4401341, 1, sparse=True)
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)

In [4]:
def search(model, user, keyword, k=10, retrieve_k=1024):
    # fix unknown keyword embedding
    candidates = [model.image_lookup[image] for image, _ in model.keyword_dict[keyword][:retrieve_k]]
    if len(candidates) < retrieve_k:
        to_sample = np.ma.array(np.arange(len(model.all_images)), mask=False)
        to_sample.mask[candidates] = True
        candidates += np.random.choice(to_sample.compressed(), retrieve_k-len(candidates), replace=False).tolist()
    
    user_id = [model.user_lookup[user]] * len(candidates)
    keyword_id = [model.keyword_lookup[keyword]] * len(candidates)
    x = torch.tensor([user_id, candidates, keyword_id]).T.cuda()
    return x
    # breakpoint()
    # scores = self.model(x).detach().flatten()
    # _, image_ids = torch.topk(scores, k)
    # # breakpoint()
    # return [self.all_images[image_id] for image_id in image_ids.cpu().detach().numpy()]

In [12]:
print(len(fm_model.keyword_dict))
print(fm_model.keyword_dict['lasdkfaklnsdf'])
print(len(fm_model.keyword_dict))

28806
[]
28807


In [8]:
userid = '2f9c6ac4-02c8-4d0f-82b3-0482a82ab0bf'
x = search(fm_model, userid, 'nternal threadpool by setting t')
# x[:1]
fm_model.model.eval()
fm_model.model(x)

tensor([1.0000, 0.9954, 0.9918,  ..., 1.0000, 1.0000, 0.0016], device='cuda:0',
       grad_fn=<ViewBackward0>)

In [6]:
x

tensor([[    3, 10613, 28806],
        [    3, 13905, 28806],
        [    3, 18149, 28806],
        ...,
        [    3, 15025, 28806],
        [    3,  7037, 28806],
        [    3, 14174, 28806]])